apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rollback
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Lhuckaz/argocd-rollback.git
    path: charts/argocd-rollback
    targetRevision: HEAD
    helm:
      parameters:
        - name: deployment.tag
          value: $ARGOCD_APP_REVISION
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
